#!/bin/sh
docker stop discourse-build-postgres  > /dev/null 2>&1 || true
docker stop discourse-build-redis  > /dev/null 2>&1 || true
docker network rm discourse-build-nw  > /dev/null 2>&1 || true
docker rm discourse-build-postgres  > /dev/null 2>&1 || true
docker rm discourse-build-redis  > /dev/null 2>&1 || true
